/* Search index — bilingual. Edit these entries when adding/removing content. */
window.SEARCH_INDEX = [
  // ----- Pre-install -----
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html',
    title: 'Qualcomm 帳號註冊', titleEn: 'Register Qualcomm account',
    body: '開始前先到 qualcomm.com 註冊（務必用公司信箱），QSC 登入與 AI Hub 都會用到',
    bodyEn: 'Register at qualcomm.com first (use your company email) — needed for QSC sign-in and AI Hub.',
    tags: ['qualcomm', 'account', '帳號', 'register', '公司信箱'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-qsc',
    title: 'Qualcomm Software Center (QSC)', titleEn: 'Qualcomm Software Center (QSC)',
    body: '下載 PCAT / QUD 的入口，安裝後以 Qualcomm 帳號登入；登入失敗請先簽署 qualcomm.com/agreements',
    bodyEn: 'Gateway to download PCAT / QUD; sign in with your Qualcomm account. Login fails? Sign the agreements at qualcomm.com/agreements.',
    tags: ['qsc', 'software center', 'qualcomm', 'agreements'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-pcat',
    title: 'PCAT Tool', titleEn: 'PCAT Tool',
    body: '燒錄 image 工具，在 QSC 的 Tools 搜尋 Product Configuration Assistant Tool',
    bodyEn: 'Image flashing tool. Search Product Configuration Assistant Tool in QSC Tools.',
    tags: ['pcat', 'flash', '燒錄', 'image'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-qud',
    title: 'QUD (Qualcomm USB Driver)', titleEn: 'QUD (Qualcomm USB Driver)',
    body: 'Qualcomm USB 驅動，從 QSC 的 Tools 下載安裝；一次只能安裝一個工具',
    bodyEn: 'Qualcomm USB driver, installed from QSC Tools. Install only one tool at a time.',
    tags: ['qud', 'usb', 'driver', '驅動', 'no logs found'] },
  { page: 'pre-install', pageLabel: '預先安裝 / PRE-INSTALL', href: 'pre-install.html#win-docker',
    title: 'WSL + Ubuntu Setup', titleEn: 'WSL + Ubuntu Setup',
    body: '安裝 WSL2 Ubuntu-22.04：wsl.exe --install -d Ubuntu-22.04，用 wsl.exe --list --verbose 確認安裝成功',
    bodyEn: 'Install WSL2 Ubuntu-22.04: wsl.exe --install -d Ubuntu-22.04, then verify with wsl.exe --list --verbose.',
    tags: ['wsl', 'ubuntu-22.04', 'wsl.exe', 'setup', '安裝'] },

  // ----- Flashing -----
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s1',
    title: '準備電路板（切到 EDL mode）', titleEn: 'Prepare the board (jumper to EDL mode)',
    body: '燒錄前務必先拔掉裝置電源，再把板子背面的跳帽調整到 EDL mode',
    bodyEn: 'Unplug the device power first, then set the jumper on the bottom of the board to EDL mode.',
    tags: ['edl mode', 'jumper', '跳帽', '拔電源', 'prepare'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s2',
    title: '打開 xPCATApp', titleEn: 'Open xPCATApp',
    body: '請確保裝置已開機才能被找到；打開後確認 "x"PCATApp 是否有成功啟動',
    bodyEn: 'Make sure the device is powered on so it can be detected, then confirm "x"PCATApp opened successfully.',
    tags: ['xpcatapp', 'pcat', 'qsc', '開機'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s3',
    title: '連線 Q911', titleEn: 'Connect to the Q911',
    body: '點擊左上角 icon，並選擇要連線的 Q911',
    bodyEn: 'Click the top-left icon and select the Q911 to connect.',
    tags: ['q911', 'connect', '連線', 'pcat'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s4',
    title: '點擊 download 選項', titleEn: 'Click the download option',
    body: '點擊左側的 download 選項，準備選擇要燒錄的 image',
    bodyEn: 'Click the download option on the left side to pick the image to flash.',
    tags: ['download', '燒錄', 'pcat'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s5',
    title: '選擇 image 與 UFS memory type', titleEn: 'Choose image and UFS memory type',
    body: '選擇 workshop_exmp-q911_v2.3.3_image 資料夾、UFS 作為 memory type，確認 .elf 被正確選擇後點 download',
    bodyEn: 'Select the workshop_exmp-q911_v2.3.3_image folder, UFS as the memory type, confirm the .elf is selected, then click download.',
    tags: ['ufs', 'memory type', 'elf', 'image', 'workshop_exmp-q911'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s6',
    title: '完成燒錄', titleEn: 'Flashing complete',
    body: '燒錄完成後即可進行後續切回 Normal mode 的步驟',
    bodyEn: 'Once flashing finishes, continue on to switching back to Normal mode.',
    tags: ['flashing complete', '燒錄完成'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s7',
    title: '拔掉電源後切回 Normal mode，並開機', titleEn: 'Power off, switch to Normal mode, then boot',
    body: '燒錄成功後請先斷電，再把跳帽調回 Normal mode',
    bodyEn: 'After a successful flash, power off the device, then set the jumper back to Normal mode.',
    tags: ['normal mode', '跳帽', '斷電', 'jumper'] },
  { page: 'flashing', pageLabel: '燒錄映像 / FLASHING', href: 'flashing.html#s8',
    title: '接上螢幕、滑鼠，啟動進入系統', titleEn: 'Boot into the System',
    body: '切回 Normal mode 後接上螢幕、滑鼠與電源開機；點擊左上方紅色 ICON 出現版本號代表燒錄成功',
    bodyEn: 'After switching back to Normal mode, connect the monitor, mouse, and power to boot; click the red icon in the top-left — a version number confirms a successful flash.',
    tags: ['boot', '開機', 'q911', 'red icon'] },

  // ----- Script: prerequisites & package -----
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#prereqs',
    title: '你需要準備什麼（前置需求）', titleEn: 'What you\'ll need (prerequisites)',
    body: 'Host x86 Windows 11、EXMP-Q911（USB-C 連接）、DP 螢幕、Qualcomm AI Hub API token；Step 4、5.2 僅連網模式才需要網路',
    bodyEn: 'Host x86 Windows 11, EXMP-Q911 via USB-C, a DP monitor, Qualcomm AI Hub API token; Steps 4 and 5.2 only need internet in online mode.',
    tags: ['prerequisites', '前置需求', 'host', 'q911', 'ai hub', 'token', '需求'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#package-layout',
    title: '資料夾裡有什麼（套件結構）', titleEn: 'What\'s in the package (layout)',
    body: 'scripts/、github/iQ-Foundry/、github/iQ-Studio/、export_qai_fp32/、iqf_save/、iqs_config/、docker_images/、streampipe/、.agent/、README',
    bodyEn: 'scripts/, github/iQ-Foundry/, github/iQ-Studio/, export_qai_fp32/, iqf_save/, iqs_config/, docker_images/, streampipe/, .agent/, README',
    tags: ['package layout', '套件結構', 'iqf_save', 'streampipe', 'docker_images', 'iqs_config', 'agent', 'readme'] },

  // ----- Script -----
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s0',
    title: 'Windows 主機設定（僅需一次）', titleEn: 'Windows Host Setup (one-time)',
    body: '[WIN-PS] 執行 setup-windows-wsl.ps1，準備 WSL2 Ubuntu-22.04、啟用 systemd，用 usbipd 掛載 Q911 USB',
    bodyEn: '[WIN-PS] Run setup-windows-wsl.ps1 to prepare WSL2 Ubuntu-22.04, enable systemd, attach the Q911 USB via usbipd.',
    tags: ['wsl', 'usbipd', 'powershell', 'script', '腳本', 'setup-windows-wsl'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s1',
    title: 'step_1.sh — 安裝 adb，確認 Q911 連線', titleEn: 'step_1.sh — Install adb, check Q911 connection',
    body: '[HOST] 約 1 分鐘，adb devices 應列出 EXMP-Q911',
    bodyEn: '[HOST] ~1 min. adb devices should list EXMP-Q911.',
    tags: ['adb', 'step_1', 'q911', 'connection'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s2',
    title: 'step_2.sh — 安裝 Docker，取得 iQ-Foundry image', titleEn: 'step_2.sh — Install Docker, get iQ-Foundry image',
    body: '[HOST] 安裝 Docker Engine，pull innodiskorg/iqf:latest',
    bodyEn: '[HOST] Install Docker Engine, pull innodiskorg/iqf:latest.',
    tags: ['docker', 'step_2', 'iqf'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s3',
    title: 'step_3.sh — 登入 Qualcomm AI Hub', titleEn: 'step_3.sh — Log in to Qualcomm AI Hub',
    body: '[HOST] step_3.sh <YOUR_QAI_HUB_API_KEY>，換成自己的 API token；此登入是 Step 4.1、5.2 連網模式才需要的',
    bodyEn: '[HOST] step_3.sh <YOUR_QAI_HUB_API_KEY> — use your own API token; only needed by Step 4.1 and 5.2\'s online mode.',
    tags: ['ai hub', 'qaihub', 'token', 'login', '登入', 'step_3'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s4',
    title: 'step_4_offline.sh — 推送離線 FP32 bundle，執行 FP32 streampipe 9ch（離線，預設）', titleEn: 'step_4_offline.sh — Push offline FP32 bundle, run FP32 streampipe 9ch (offline, default)',
    body: '[Q911 約 3 分 45 秒] 不需連網，使用套件內附的 FP32 bundle 推送並啟動 streampipe 9ch；畫面出現後可接上相機',
    bodyEn: '[Q911, ~3 min 45 sec] No internet needed — uses the bundled FP32 bundle to push and start streampipe 9ch; connect the camera once the screen appears.',
    tags: ['fp32', 'streampipe', 'offline', '離線', 'step_4_offline', '9ch', 'camera', '相機'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s4',
    title: 'step_4_1.sh + step_4_2.sh — FP32 匯出，安裝 iQ-Studio 並執行 streampipe（連網）', titleEn: 'step_4_1.sh + step_4_2.sh — FP32 export, install iQ-Studio and run streampipe (online)',
    body: '[HOST · AI Hub] 建置 iqf-aihub image 匯出 FP32 TFLite；[Q911 首次執行 ~3 分鐘] 推送並安裝 iQ-Studio，啟動 FP32 streampipe 9ch，畫面出現後可接上相機',
    bodyEn: '[HOST · AI Hub] Build the iqf-aihub image, export FP32 TFLite; [Q911, ~3 min first run] push and install iQ-Studio, start FP32 streampipe 9ch — connect the camera once the screen appears.',
    tags: ['fp32', 'export', 'yolo26', 'tflite', 'iq-studio', 'streampipe', 'online', '連網', 'step_4_1', 'step_4_2', '9ch', 'camera', '相機'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_1',
    title: 'step_5_1.sh — 部署 Q911 runtime venv', titleEn: 'step_5_1.sh — Deploy Q911 runtime venv',
    body: '[離線] 部署裝置端 venv，adb kill-server 讓出 USB 給 container；host 端 adb 到 Step 5.5 才會恢復',
    bodyEn: '[Offline] Deploy the device-side venv, adb kill-server to release USB for the container; host-side adb comes back at Step 5.5.',
    tags: ['venv', 'q911', 'step_5_1', 'adb kill-server'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_2',
    title: 'step_5_2_offline.sh — 複製預先量化好的 INT8 模型（離線，預設）', titleEn: 'step_5_2_offline.sh — Copy the pre-quantized INT8 model (offline, default)',
    body: '[HOST 約 3 秒] 不需連上 AI Hub，複製套件內預先量化好的 INT8 模型',
    bodyEn: '[HOST, ~3 sec] No AI Hub connection needed — copies the pre-quantized INT8 model included in the package.',
    tags: ['quantization', '量化', 'int8', 'offline', '離線', 'step_5_2_offline'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_2',
    title: 'step_5_2.sh — INT8 量化 qc（連網）', titleEn: 'step_5_2.sh — INT8 quantization qc (online)',
    body: '[HOST · AI Hub] qc 量化，把 YOLO26 .pt 量化成 INT8 .tflite',
    bodyEn: '[HOST · AI Hub] qc quantization — quantize YOLO26 .pt into an INT8 .tflite.',
    tags: ['quantization', '量化', 'int8', 'iqf', 'qc', 'online', '連網', 'step_5_2'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_3',
    title: 'step_5_3.sh — mAP 比較：FP32 vs INT8', titleEn: 'step_5_3.sh — mAP comparison (FP32 vs INT8)',
    body: '[離線] 執行 step_5_3.sh 進行 mAP 評估，完成後到 github/iQ-Foundry/out/mAP/yolo26/ 查看結果',
    bodyEn: '[Offline] Run step_5_3.sh for the mAP evaluation, then check the results at github/iQ-Foundry/out/mAP/yolo26/.',
    tags: ['map', 'mAP', 'iqf', 'evaluation', '評估', 'step_5_3'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_4',
    title: 'step_5_4.sh — iQ-Foundry 裝置端測試', titleEn: 'step_5_4.sh — iQ-Foundry on-device test',
    body: '[離線] 透過 adb 在 Q911 上跑 INT8 模型推論；可點開輸入/輸出圖片預覽',
    bodyEn: '[Offline] Run INT8 model inference on the Q911 via adb; input/output image previews available.',
    tags: ['device test', '裝置測試', 'adb', 'iqf', 'int8', 'step_5_4', 'images', '圖片'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_5',
    title: 'step_5_5_offline.sh — 推送離線 INT8 bundle，執行 streampipe 9ch（離線，預設）', titleEn: 'step_5_5_offline.sh — Push offline INT8 bundle, run streampipe 9ch (offline, default)',
    body: '[Q911 約 40 秒] 不需連網，使用套件內附的 INT8 bundle 推送並啟動 streampipe 9ch',
    bodyEn: '[Q911, ~40 sec] No internet needed — uses the bundled INT8 bundle to push and start streampipe 9ch.',
    tags: ['int8', 'streampipe', 'offline', '離線', 'step_5_5_offline', '9ch'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s5_5',
    title: 'step_5_5.sh — 執行 INT8 streampipe 9ch（連網）', titleEn: 'step_5_5.sh — Run INT8 streampipe 9ch (online)',
    body: '[Q911] 推送 INT8 模型/設定檔，啟動 INT8 streampipe 9ch，並執行 adb start-server 恢復 host 端 adb',
    bodyEn: '[Q911] Push the INT8 model/config, start INT8 streampipe 9ch, and run adb start-server to restore host-side adb.',
    tags: ['int8', 'streampipe', 'online', '連網', 'step_5_5', '9ch', 'adb start-server'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT', href: 'script.html#s6',
    title: '正確關閉 WSL', titleEn: 'Properly shut down WSL',
    body: '[WSL] Ctrl+C 後會停留在 WSL 裡，先 exit 再執行 wsl --shutdown',
    bodyEn: '[WSL] After Ctrl+C you land back in the WSL shell — exit, then run wsl --shutdown.',
    tags: ['wsl', 'shutdown', '關閉', 'exit', 'wsl --shutdown', 'step_6'] },

  // ----- Script: troubleshooting -----
  { page: 'script', pageLabel: '腳本 / SCRIPT · 疑難排解', href: 'script.html#s1',
    title: 'STEP_1~5.2、5.5 疑難排解：Q911 沒被 lsusb 看到', titleEn: 'STEP_1~5.2, 5.5 troubleshooting: Q911 missing from lsusb',
    body: 'lsusb 只有 root hub、沒有 911 裝置 → exit 回 PowerShell → 重新執行 setup-windows-wsl.ps1 → 再跑一次 lsusb 確認',
    bodyEn: 'lsusb only shows root hubs, no 911 device → exit back to PowerShell → rerun setup-windows-wsl.ps1 → run lsusb again to confirm.',
    tags: ['lsusb', 'troubleshoot', '疑難排解', 'q911', 'usb', 'exit', 'setup-windows-wsl'] },
  { page: 'script', pageLabel: '腳本 / SCRIPT · 疑難排解', href: 'script.html#s5_3',
    title: 'STEP_5.3、5.4 疑難排解：Q911 沒被 lsusb 看到', titleEn: 'STEP_5.3, 5.4 troubleshooting: Q911 missing from lsusb',
    body: 'lsusb 只有 root hub、沒有 911 裝置 → exit 回 PowerShell → 重新執行 setup-windows-wsl.ps1 → 加執行 adb kill-server',
    bodyEn: 'lsusb only shows root hubs, no 911 device → exit back to PowerShell → rerun setup-windows-wsl.ps1 → also run adb kill-server.',
    tags: ['lsusb', 'troubleshoot', '疑難排解', 'q911', 'usb', 'adb kill-server'] },

  // ----- Agenda (on homepage) -----
  { page: 'agenda', pageLabel: '議程 / AGENDA', href: 'index.html#agenda',
    title: '議程 Agenda', titleEn: 'Agenda',
    body: '2026.07.30（四）10:00–16:00，新北市汐止區大同路一段 237 號 16 樓',
    bodyEn: 'Thu 2026.07.30, 10:00–16:00 — 16F, No.237, Sec.1, Datong Rd, Xizhi, New Taipei.',
    tags: ['agenda', '議程', 'schedule', '時間', '地點', '報到', '開場', '結尾'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 10:10', href: 'index.html#agenda',
    title: '高通技術公司 — 呂承翰', titleEn: 'Qualcomm — 呂承翰',
    body: '10:10–10:40 呂承翰，Director, Business Development, Qualcomm',
    bodyEn: '10:10–10:40 呂承翰, Director, Business Development, Qualcomm.',
    tags: ['qualcomm', '高通', '呂承翰', 'business development'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 10:40', href: 'index.html#agenda',
    title: '高通邊緣平台如何重塑智慧生態系 — 吳志清', titleEn: 'Reshaping the smart ecosystem — 吳志清',
    body: '10:40–11:05 宜鼎國際 Innodisk，吳志清 智能周邊應用事業處處長',
    bodyEn: '10:40–11:05 Innodisk, 吳志清, Head of Smart Peripheral Application.',
    tags: ['innodisk', '宜鼎', '吳志清', '邊緣平台', '生態系', 'edge'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 11:05', href: 'index.html#agenda',
    title: '用 Edge Impulse 簡化 Edge AI 開發與部署流程 — 林宣百', titleEn: 'Simplify Edge AI with Edge Impulse — 林宣百',
    body: '11:05–11:30 Edge Impulse Inc.，林宣百 技術應用工程師, 高通技術公司',
    bodyEn: '11:05–11:30 Edge Impulse Inc., 林宣百, FAE, Qualcomm.',
    tags: ['edge impulse', '林宣百', 'edge ai', '部署', 'deploy'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 11:30', href: 'index.html#agenda',
    title: '高效率 AI On-Prem 解決方案實現 Edge LLM 規模化部署 — 施良岳', titleEn: 'Scalable Edge LLM with AI On-Prem — 施良岳',
    body: '11:30–11:55 安提國際 Aetina，施良岳 MegaEdge 邊緣運算平台 產品部副理',
    bodyEn: '11:30–11:55 Aetina, 施良岳, MegaEdge Product Manager.',
    tags: ['aetina', '安提', '施良岳', 'on-prem', 'edge llm', 'megaedge', 'llm'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 11:55', href: 'index.html#agenda',
    title: 'Trusted Agentic AI Beyond the Cloud — 鍾哲民', titleEn: 'Trusted Agentic AI Beyond the Cloud — 鍾哲民',
    body: '11:55–12:20 行動貝果 MoBagel，鍾哲民 美商行動貝果 執行長暨共同創辦人',
    bodyEn: '11:55–12:20 MoBagel, 鍾哲民, CEO & Co-founder.',
    tags: ['mobagel', '行動貝果', '鍾哲民', 'agentic ai', 'cloud'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 13:30', href: 'index.html#agenda',
    title: 'IQ9 實作演練 I — 黃誌祥', titleEn: 'IQ9 Hands-on I — 黃誌祥',
    body: '13:30–14:30 1. IQ Studio 平台概覽 2. 韌體燒錄 & 環境初始化｜黃誌祥 智能周邊應用事業處軟體研發部副理',
    bodyEn: '13:30–14:30 1. IQ Studio overview 2. Firmware flashing & environment init. 黃誌祥.',
    tags: ['iq9', 'iq studio', '黃誌祥', '韌體', '燒錄', '實作演練', 'hands-on'] },
  { page: 'agenda', pageLabel: '議程 / AGENDA · 14:50', href: 'index.html#agenda',
    title: 'IQ9 實作演練 II — 黃誌祥', titleEn: 'IQ9 Hands-on II — 黃誌祥',
    body: '14:50–15:50 1. 高通模型下載與優化轉換 2. 模型轉換與部屬 AI PoC 展示與驗證｜黃誌祥',
    bodyEn: '14:50–15:50 1. Qualcomm model download & optimization 2. Model conversion & AI PoC demo. 黃誌祥.',
    tags: ['iq9', '模型', '優化', 'poc', '黃誌祥', '實作演練', 'hands-on', 'model'] },

  // ----- Handouts -----
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: '攜帶清單', titleEn: 'What to bring',
    body: '自備：Windows 11 筆電（已裝好工具）；現場提供：EXMP-Q911、type-c to USB、DP2HDMI、HDMI2HDMI、螢幕、UVC camera',
    bodyEn: 'Bring yourself: a Windows 11 laptop (with tools installed); provided on-site: EXMP-Q911, type-c to USB, DP2HDMI, HDMI2HDMI, monitor, UVC camera.',
    tags: ['checklist', '攜帶', 'q911', 'camera', 'hdmi', 'windows 11'] },
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: '建立 Qualcomm 帳號', titleEn: 'Create a Qualcomm account',
    body: '請事前到 qualcomm.com 建立 Qualcomm 帳號',
    bodyEn: 'Create a Qualcomm account at qualcomm.com beforehand.',
    tags: ['qualcomm', 'account', '帳號'] },
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: 'iQ-Studio / iQ-Foundry repo', titleEn: 'iQ-Studio / iQ-Foundry repos',
    body: 'GitHub 教材：github.com/InnoIPA/iQ-Studio、github.com/InnoIPA/iQ-Foundry',
    bodyEn: 'GitHub material: github.com/InnoIPA/iQ-Studio and github.com/InnoIPA/iQ-Foundry.',
    tags: ['github', 'iq-studio', 'iq-foundry', 'repo', 'innoipa'] },
  { page: 'handouts', pageLabel: '講義 / HANDOUTS', href: 'handouts.html',
    title: '下載檔案（共用資料夾，只開放到 8/5）', titleEn: 'Download files (shared folder, available until Aug 5)',
    body: '工作坊套件下載連結，SharePoint 共用資料夾',
    bodyEn: 'Workshop package download link, a SharePoint shared folder.',
    tags: ['download', '下載', '共用資料夾', 'shared folder', 'sharepoint', '8/5'] },
];
